[package]
name = "impl-if"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
def-call = { path = "../def-call" }
crate_interface = { path = "../crate_interface" }
